title: Greenify Supply chains
logo: /assets/img/Greenify_logo.png
description: Making the world a better place through greener and less carbon intensive procurements.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman