title: Greenify procurement
logo: /assets/img/Greenify_logo_2.png
description: Our CO2 and procurement analytics helps you make vendor choices that saves both money and the planet
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman